from core import PlantComponent
from streams import WaterStream


class Pretreatment(PlantComponent):
    """
    Pretreatment stage.

    Boundary:
        Post-Intake -> Pre-RO

    Includes:
        - Media filtration
        - Cartridge filtration
        - Chemical dosing
        - High-pressure pumping

    All output properties are calculated from configurable
    model parameters rather than directly assigned.
    """

    def __init__(
        self,
        name="Pretreatment",

        # -----------------------------
        # FILTER PARAMETERS
        # -----------------------------

        filter_age=30,
        base_filter_resistance=0.5,
        resistance_age_factor=0.02,

        # -----------------------------
        # FLOW LOSS PARAMETERS
        # -----------------------------

        base_flow_loss=0.01,
        flow_loss_age_factor=0.0002,

        # -----------------------------
        # CHEMICAL DOSING PARAMETERS
        # -----------------------------

        acid_dosing_factor=0.5,
        dosing_rate=1.0,

        # -----------------------------
        # HIGH PRESSURE PUMP
        # -----------------------------

        pump_pressure_rise=58.0
    ):

        super().__init__(name)

        # Filter condition
        self.filter_age = filter_age
        self.base_filter_resistance = base_filter_resistance
        self.resistance_age_factor = resistance_age_factor

        # Flow loss
        self.base_flow_loss = base_flow_loss
        self.flow_loss_age_factor = flow_loss_age_factor

        # Chemical dosing
        self.acid_dosing_factor = acid_dosing_factor
        self.dosing_rate = dosing_rate

        # Pump
        self.pump_pressure_rise = pump_pressure_rise

    # ==================================================
    # FILTER MODEL
    # ==================================================

    def calculate_filter_resistance(self):
        """
        Calculate filter pressure resistance.

        Model:

            R = R_base + k_age * filter_age
        """

        resistance = (
            self.base_filter_resistance
            + self.resistance_age_factor * self.filter_age
        )

        return resistance

    # ==================================================
    # FLOW LOSS MODEL
    # ==================================================

    def calculate_flow_loss_fraction(self):
        """
        Calculate fraction of water lost through backwash /
        filtration operations.

        Model:

            L = L_base + k_age_flow * filter_age
        """

        loss_fraction = (
            self.base_flow_loss
            + self.flow_loss_age_factor * self.filter_age
        )

        # Prevent physically unreasonable values.
        return min(max(loss_fraction, 0), 0.10)

    # ==================================================
    # PH MODEL
    # ==================================================

    def calculate_acid_dosing_effect(self):
        """
        Calculate pH reduction caused by chemical dosing.

        Simplified initial model:

            ΔpH = acid_dosing_factor × dosing_rate
        """

        delta_pH = (
            self.acid_dosing_factor
            * self.dosing_rate
        )

        return delta_pH

    def calculate_output_pH(self, input_pH):
        """
        Calculate pH after chemical dosing.
        """

        acid_effect = self.calculate_acid_dosing_effect()

        output_pH = input_pH - acid_effect

        # Keep pH within physical bounds.
        return max(0, min(14, output_pH))

    # ==================================================
    # HIGH PRESSURE PUMP MODEL
    # ==================================================

    def calculate_pump_pressure_rise(self):
        """
        Calculate pressure increase generated by HPP.

        For now this is a configurable pump operating parameter.
        """

        return self.pump_pressure_rise

    # ==================================================
    # MAIN PROCESS
    # ==================================================

    def process(self, water_stream):

        if not isinstance(water_stream, WaterStream):
            raise TypeError(
                "Pretreatment expects a WaterStream object"
            )

        # ----------------------------------------------
        # 1. FILTER RESISTANCE
        # ----------------------------------------------

        filter_resistance = (
            self.calculate_filter_resistance()
        )

        # ----------------------------------------------
        # 2. PRESSURE DROP THROUGH FILTER
        # ----------------------------------------------

        filtered_pressure = max(
            0,
            water_stream.pressure - filter_resistance
        )

        # ----------------------------------------------
        # 3. FLOW LOSS
        # ----------------------------------------------

        flow_loss_fraction = (
            self.calculate_flow_loss_fraction()
        )

        output_flow = (
            water_stream.flow
            * (1 - flow_loss_fraction)
        )

        # ----------------------------------------------
        # 4. CHEMICAL DOSING / pH
        # ----------------------------------------------

        output_pH = self.calculate_output_pH(
            water_stream.pH
        )

        # ----------------------------------------------
        # 5. HIGH PRESSURE PUMP
        # ----------------------------------------------

        pump_pressure_rise = (
            self.calculate_pump_pressure_rise()
        )

        pre_ro_pressure = (
            filtered_pressure
            + pump_pressure_rise
        )

        # ----------------------------------------------
        # 6. CREATE OUTPUT STREAM
        # ----------------------------------------------

        return water_stream.copy(
            name="Pre-RO",
            flow=output_flow,
            pressure=pre_ro_pressure,
            temperature=water_stream.temperature,
            salinity=water_stream.salinity,
            pH=output_pH
        )
    